name: Terraform Destroy

on:
  workflow_dispatch:  # Allows manual triggering
    inputs:
      environment:
        description: 'Environment to destroy'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - production
      confirm_destroy:
        description: 'Type "destroy" to confirm'
        required: true
        type: string

env:
  TF_VERSION: 1.5.0
  AWS_REGION: us-east-1

jobs:
  terraform-destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
    - name: Check confirmation
      run: |
        if [ "${{ github.event.inputs.confirm_destroy }}" != "destroy" ]; then
          echo "❌ Destruction not confirmed. Please type 'destroy' to confirm."
          exit 1
        fi
        echo "✅ Destruction confirmed"

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Init
      run: terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Terraform Plan Destroy
      run: terraform plan -destroy -out=tfdestroyplan
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Terraform Destroy
      run: terraform apply -auto-approve tfdestroyplan
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Notify Destroy Completion
      run: |
        echo "✅ Terraform destroy completed successfully for environment: ${{ github.event.inputs.environment }}"
